### ISSUE TITLE
Pictures attachments

### ISSUE THREAD

**Issue by mgoljak** [gsurrel/FacebookNotifications#19]
Hi, I'm unable to add picture attachments in messages. can you please work this out

**Comment by dylanrees** [comment]
Seconded.  I'm having the same issue.

**Comment by gsurrel** [comment]
I've implemented it

**Comment by dylanrees** [comment]
Thanks for looking at this!  Unfortunately it's still not working for me.  I've got the same issue as before; namely if I select "Add Photos" in a chat, I'm given three "Choose File" buttons but pressing them doesn't appear to do anything.

**Comment by gsurrel** [comment]
That's interesting. Which version are you using? Fdroid, Play Store, Github debug/release?

**Comment by dylanrees** [comment]
I'm on the F-droid version.

**Comment by gsurrel** [comment]
It seems fdroid has not detected yet the new version: it still displays v1.8.0. Be sure to check to have v1.9.2 :)

**Comment by dylanrees** [comment]
I tried installing it via Play Store and it worked!  Thanks!
